In [3]:
import numpy as np
n=np.array([1,2,3])
print(n)
print(type(n))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
n=np.array(54)
print(n.ndim)         # to know dimension that is 0
print(n)

0
54


In [9]:
import numpy as np
n=np.array([[1,2,3],[4,5,6]])
print(n)
print(n.ndim)

[[1 2 3]
 [4 5 6]]
2


In [10]:
#inlizations with zeros
import numpy as np
n=np.zeros([2,3])
print(n)
print(n.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
2


In [12]:
import numpy as np
n=np.array([2,3])
print(n)
print(n.ndim)

[2 3]
1


In [13]:
import numpy as np
n=np.zeros([4,4])
print(n)
print(n.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


In [15]:
import numpy as np
n=np.array([1,2,3])
print(n)
print(n.dtype)
print(type(n))

[1 2 3]
int32
<class 'numpy.ndarray'>


In [16]:
import numpy as np
n=np.array(["jyothi","ram","vani"])
print(n)
print(type(n))
print(n.dtype)
print(n.ndim)

['jyothi' 'ram' 'vani']
<class 'numpy.ndarray'>
<U6
1


In [17]:
import numpy as np
n=np.array(["a","b","c"])
print(n)
print(n.dtype)
print(type(n))
print(n.ndim)

['a' 'b' 'c']
<U1
<class 'numpy.ndarray'>
1


In [23]:
import numpy as np
n=np.array(["jyothi","ram"],dtype='S5')
print(n.dtype)
print(type(n))
print(n.ndim)
print(n)

|S5
<class 'numpy.ndarray'>
1
[b'jyoth' b'ram']


In [24]:
import numpy as np
n=np.array(["j","r"],dtype='S5')
print(n.dtype)
print(type(n))
print(n.ndim)
print(n)

|S5
<class 'numpy.ndarray'>
1
[b'j' b'r']


In [29]:
import numpy as np
n=np.array(['10','21','31'])
print(n)
print(n.dtype)
n1=n.astype('i')
print(n1)
print(n1.dtype)


['10' '21' '31']
<U2
[10 21 31]
int32


In [21]:
#indexing
import numpy as np
n=np.array([1,2,3])
print(n)
print(n[0])
print(n[-1])

[1 2 3]
1
3


In [22]:
import numpy as np
n=np.array([[1,2,3],[4,5,6]])
print(n)
print(n[0,0])
print(n[0,1])
print(n[0,2])
print(n[1,0])
print(n[1,1])
print(n[1,2])
print(n[1,-1])

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6
6


In [20]:
import numpy as np
n=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[6,3,9]]])
print(n)
print(n[0,0])
print(n[0,1])
print(n[1,0])
print(n[1,1])
print(n.ndim)


[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [6 3 9]]]
[1 2 3]
[4 5 6]
[7 8 9]
[6 3 9]
3


In [2]:
# itarating numpy 1 dim arrays
import numpy as np
n=np.array([1,2,3,4])
print(n)
print(type(n))
print(n.dtype)
print(n.ndim)
for i in n:
    print(i)

[1 2 3 4]
<class 'numpy.ndarray'>
int32
1
1
2
3
4


In [6]:
# itrating numpy 2 dim array
import numpy as np
n=np.array([[1,2,3],[4,5,6]])
print(n)
print(type(n))
print(n.dtype)
print(n.ndim)
for i in n:
    print(i)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int32
2
[1 2 3]
[4 5 6]


In [11]:
# joining of tow or more arrays
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([5,6,7,8])
join=np.concatenate((n1,n2))
print(join)
for i in n1:
    print(i)
for j in n2:
    print(j)

[1 2 3 4 5 6 7 8]
1
2
3
4
5
6
7
8
